FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN mkdir -p /home/root/src
WORKDIR /home/root/src

COPY ../pyproject.toml ../uv.lock ./
RUN uv sync --frozen

CMD ["uv", "run", "fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]
